export default [
  { id: '3D Modeling', text: '3D Modeling' },
  { id: 'Adobe Illustrator', text: 'Adobe Illustrator' },
  { id: 'Adobe InDesign', text: 'Adobe InDesign' },
  { id: 'Adobe Photoshop', text: 'Adobe Photoshop' },
  { id: 'Agile Methodologies', text: 'Agile Methodologies' },
  { id: 'Alibaba Cloud', text: 'Alibaba Cloud' },
  { id: 'Animation', text: 'Animation' },
  { id: 'ASP.NET', text: 'ASP.NET' },
  { id: 'Auth0', text: 'Auth0' },
  { id: 'Autodesk AutoCAD', text: 'Autodesk AutoCAD' },
  { id: 'Blockchain', text: 'Blockchain' },
  { id: 'Bokeh', text: 'Bokeh' },
  { id: 'C#', text: 'C#' },
  { id: 'C++', text: 'C++' },
  { id: 'CAD/CAM Design', text: 'CAD/CAM Design' },
  { id: 'Cardano', text: 'Cardano' },
  { id: 'CI/CD', text: 'CI/CD' },
  { id: 'Community Governance', text: 'Community Governance' },
  { id: 'Cloud Computing', text: 'Cloud Computing' },
  { id: 'Computer Vision', text: 'Computer Vision' },
  { id: 'Confluence', text: 'Confluence' },
  { id: 'Containerization', text: 'Containerization' },
  { id: 'CSS', text: 'CSS' },
  { id: 'Cybersecurity', text: 'Cybersecurity' },
  { id: 'D3.js', text: 'D3.js' },
  { id: 'Deep Learning', text: 'Deep Learning' },
  { id: 'DevOps', text: 'DevOps' },
  { id: 'Django', text: 'Django' },
  { id: 'Docker', text: 'Docker' },
  { id: 'DigitalOcean', text: 'DigitalOcean' },
  { id: 'Encryption', text: 'Encryption' },
  { id: 'ERP Systems', text: 'ERP Systems' },
  { id: 'Ethereum', text: 'Ethereum' },
  { id: 'Express.js', text: 'Express.js' },
  { id: 'Firebase', text: 'Firebase' },
  { id: 'Flask', text: 'Flask' },
  { id: 'Flutter', text: 'Flutter' },
  { id: 'Git', text: 'Git' },
  { id: 'GitHub', text: 'GitHub' },
  { id: 'GitLab', text: 'GitLab' },
  { id: 'Go', text: 'Go' },
  { id: 'Google Workspace', text: 'Google Workspace' },
  { id: 'GraphQL', text: 'GraphQL' },
  { id: 'Heroku', text: 'Heroku' },
  { id: 'HTML', text: 'HTML' },
  { id: 'IBM Cloud', text: 'IBM Cloud' },
  { id: 'Incident Response', text: 'Incident Response' },
  { id: 'IPFS', text: 'IPFS' },
  { id: 'Ionic', text: 'Ionic' },
  { id: 'Java', text: 'Java' },
  { id: 'JavaScript', text: 'JavaScript' },
  { id: 'Jenkins', text: 'Jenkins' },
  { id: 'JIRA', text: 'JIRA' },
  { id: 'JWT', text: 'JWT' },
  { id: 'Kanban', text: 'Kanban' },
  { id: 'Keras', text: 'Keras' },
  { id: 'Kotlin', text: 'Kotlin' },
  { id: 'Laravel', text: 'Laravel' },
  { id: 'Lean', text: 'Lean' },
  { id: 'Litecoin', text: 'Litecoin' },
  { id: 'Machine Learning', text: 'Machine Learning' },
  { id: 'Matplotlib', text: 'Matplotlib' },
  { id: 'Microsoft Teams', text: 'Microsoft Teams' },
  { id: 'Microservices', text: 'Microservices' },
  { id: 'MongoDB', text: 'MongoDB' },
  { id: 'Motion Graphics', text: 'Motion Graphics' },
  { id: 'Netlify', text: 'Netlify' },
  { id: 'NoSQL', text: 'NoSQL' },
  { id: 'Node.js', text: 'Node.js' },
  { id: 'NumPy', text: 'NumPy' },
  { id: 'NFTs', text: 'NFTs' },
  { id: 'OAuth', text: 'OAuth' },
  { id: 'Objective-C', text: 'Objective-C' },
  { id: 'OpenID Connect', text: 'OpenID Connect' },
  { id: 'Oracle Cloud', text: 'Oracle Cloud' },
  { id: 'Pandas', text: 'Pandas' },
  { id: 'Penetration Testing', text: 'Penetration Testing' },
  { id: 'Perl', text: 'Perl' },
  { id: 'PHP', text: 'PHP' },
  { id: 'Plotly', text: 'Plotly' },
  { id: 'Python', text: 'Python' },
  { id: 'PyTorch', text: 'PyTorch' },
  { id: 'R', text: 'R' },
  { id: 'React Native', text: 'React Native' },
  { id: 'ReactJS', text: 'ReactJS' },
  { id: 'RESTful API', text: 'RESTful API' },
  { id: 'Ruby', text: 'Ruby' },
  { id: 'Ruby on Rails', text: 'Ruby on Rails' },
  { id: 'SAML', text: 'SAML' },
  { id: 'Scikit-learn', text: 'Scikit-learn' },
  { id: 'Scrum', text: 'Scrum' },
  { id: 'Seaborn', text: 'Seaborn' },
  { id: 'Serverless', text: 'Serverless' },
  { id: 'Shell Scripting', text: 'Shell Scripting' },
  { id: 'Smart Contracts', text: 'Smart Contracts' },
  { id: 'Solidity', text: 'Solidity' },
  { id: 'Spring Framework', text: 'Spring Framework' },
  { id: 'SQL', text: 'SQL' },
  { id: 'Swift', text: 'Swift' },
  { id: 'TensorFlow', text: 'TensorFlow' },
  { id: 'Trello', text: 'Trello' },
  { id: 'TypeScript', text: 'TypeScript' },
  { id: 'User Experience Design', text: 'User Experience Design' },
  { id: 'User Interface Design', text: 'User Interface Design' },
  { id: 'Vercel', text: 'Vercel' },
  { id: 'Video Editing', text: 'Video Editing' },
  { id: 'Vue.js', text: 'Vue.js' },
  { id: 'Web3.js', text: 'Web3.js' },
  { id: 'Xamarin', text: 'Xamarin' },
  { id: 'XML', text: 'XML' },
  { id: 'Zoom', text: 'Zoom' },
  { id: 'Agile Methodology', text: 'Agile Methodology' },
  { id: 'AWS', text: 'AWS' },
  { id: 'Bán hàng', text: 'Bán hàng' },
  { id: 'Bảo hiểm', text: 'Bảo hiểm' },
  { id: 'Bảo mật mạng', text: 'Bảo mật mạng' },
  { id: 'Biên tập', text: 'Biên tập' },
  { id: 'Big Data', text: 'Big Data' },
  { id: 'Dịch thuật', text: 'Dịch thuật' },
  { id: 'Giao tiếp', text: 'Giao tiếp' },
  { id: 'Giải quyết vấn đề', text: 'Giải quyết vấn đề' },
  { id: 'Giải quyết xung đột', text: 'Giải quyết xung đột' },
  { id: 'Google Cloud Platform', text: 'Google Cloud Platform' },
  { id: 'HubSpot', text: 'HubSpot' },
  { id: 'Kế toán', text: 'Kế toán' },
  { id: 'Kế toán quản trị', text: 'Kế toán quản trị' },
  { id: 'Kỹ năng SEO', text: 'Kỹ năng SEO' },
  { id: 'Kỹ năng marketing số', text: 'Kỹ năng marketing số' },
  { id: 'Làm tóc', text: 'Làm tóc' },
  { id: 'Làm việc độc lập', text: 'Làm việc độc lập' },
  { id: 'Làm việc nhóm', text: 'Làm việc nhóm' },
  { id: 'Lập kế hoạch', text: 'Lập kế hoạch' },
  { id: 'Lập trình ASIC', text: 'Lập trình ASIC' },
  { id: 'Lập trình Android', text: 'Lập trình Android' },
  { id: 'Lập trình C#', text: 'Lập trình C#' },
  { id: 'Lập trình C++', text: 'Lập trình C++' },
  { id: 'Lập trình FPGA', text: 'Lập trình FPGA' },
  { id: 'Lập trình iOS', text: 'Lập trình iOS' },
  { id: 'Lập trình Java', text: 'Lập trình Java' },
  { id: 'Lập trình JavaScript', text: 'Lập trình JavaScript' },
  { id: 'Lập trình Kotlin', text: 'Lập trình Kotlin' },
  { id: 'Lập trình PHP', text: 'Lập trình PHP' },
  { id: 'Lập trình PLC', text: 'Lập trình PLC' },
  { id: 'Lập trình Python', text: 'Lập trình Python' },
  { id: 'Lập trình Swift', text: 'Lập trình Swift' },
  { id: 'Lập trình TypeScript', text: 'Lập trình TypeScript' },
  { id: 'Lập trình game', text: 'Lập trình game' },
  { id: 'Lập trình máy tính', text: 'Lập trình máy tính' },
  { id: 'Lập trình nhúng', text: 'Lập trình nhúng' },
  { id: 'Lập trình vi xử lý', text: 'Lập trình vi xử lý' },
  { id: 'Lập trình web', text: 'Lập trình web' },
  { id: 'Lập trình ứng dụng di động', text: 'Lập trình ứng dụng di động' },
  { id: 'Lean Methodology', text: 'Lean Methodology' },
  { id: 'Machine Learning', text: 'Machine Learning' },
  { id: 'Marketing', text: 'Marketing' },
  { id: 'May vá', text: 'May vá' },
  { id: 'Microsoft Azure', text: 'Microsoft Azure' },
  { id: 'Microsoft Dynamics', text: 'Microsoft Dynamics' },
  { id: 'Nấu ăn', text: 'Nấu ăn' },
  { id: 'Natural Language Processing', text: 'Natural Language Processing' },
  { id: 'NetSuite', text: 'NetSuite' },
  { id: 'Ngân hàng', text: 'Ngân hàng' },
  { id: 'Ngoại ngữ', text: 'Ngoại ngữ' },
  { id: 'Pha chế', text: 'Pha chế' },
  { id: 'Phân tích an ninh mạng', text: 'Phân tích an ninh mạng' },
  { id: 'Phân tích dữ liệu', text: 'Phân tích dữ liệu' },
  { id: 'Phân tích tài chính', text: 'Phân tích tài chính' },
  { id: 'Phát triển phần mềm', text: 'Phát triển phần mềm' },
  { id: 'Phát triển web', text: 'Phát triển web' },
  { id: 'Phát triển ứng dụng di động', text: 'Phát triển ứng dụng di động' },
  { id: 'Quản lý chuỗi cung ứng', text: 'Quản lý chuỗi cung ứng' },
  { id: 'Quản lý dự án', text: 'Quản lý dự án' },
  { id: 'Quản lý dự án phần mềm', text: 'Quản lý dự án phần mềm' },
  { id: 'Quản lý nhà hàng', text: 'Quản lý nhà hàng' },
  { id: 'Quản lý nhân sự', text: 'Quản lý nhân sự' },
  { id: 'Quản lý khách sạn', text: 'Quản lý khách sạn' },
  { id: 'Quản lý rủi ro', text: 'Quản lý rủi ro' },
  { id: 'Quản lý sản xuất', text: 'Quản lý sản xuất' },
  { id: 'Quản lý thời gian', text: 'Quản lý thời gian' },
  { id: 'Quản lý vận hành', text: 'Quản lý vận hành' },
  { id: 'Quản trị cơ sở dữ liệu', text: 'Quản trị cơ sở dữ liệu' },
  { id: 'Quản trị hệ thống', text: 'Quản trị hệ thống' },
  { id: 'Quản trị mạng', text: 'Quản trị mạng' },
  { id: 'Quản trị tài nguyên', text: 'Quản trị tài nguyên' },
  { id: 'Quan hệ công chúng', text: 'Quan hệ công chúng' },
  { id: 'Quảng cáo', text: 'Quảng cáo' },
  { id: 'QuickBooks', text: 'QuickBooks' },
  { id: 'SAP', text: 'SAP' },
  { id: 'Salesforce', text: 'Salesforce' },
  { id: 'Six Sigma', text: 'Six Sigma' },
  { id: 'Soạn thảo', text: 'Soạn thảo' },
  { id: 'Sửa chữa ô tô', text: 'Sửa chữa ô tô' },
  { id: 'Sửa chữa điện lạnh', text: 'Sửa chữa điện lạnh' },
  { id: 'Sửa chữa điện tử', text: 'Sửa chữa điện tử' },
  { id: 'Sửa chữa máy tính', text: 'Sửa chữa máy tính' },
  { id: 'Tạo nội dung', text: 'Tạo nội dung' },
  { id: 'Thiết kế UX/UI', text: 'Thiết kế UX/UI' },
  { id: 'Thiết kế cơ sở dữ liệu', text: 'Thiết kế cơ sở dữ liệu' },
  { id: 'Thiết kế mạch điện', text: 'Thiết kế mạch điện' },
  { id: 'Thiết kế mạng máy tính', text: 'Thiết kế mạng máy tính' },
  { id: 'Thiết kế nội thất', text: 'Thiết kế nội thất' },
  { id: 'Thiết kế PCB', text: 'Thiết kế PCB' },
  { id: 'Thiết kế thời trang', text: 'Thiết kế thời trang' },
  { id: 'Thiết kế vi mạch', text: 'Thiết kế vi mạch' },
  { id: 'Thiết kế web', text: 'Thiết kế web' },
  { id: 'Thiết kế đồ họa', text: 'Thiết kế đồ họa' },
  { id: 'Thị trường tài chính', text: 'Thị trường tài chính' },
  { id: 'Thiết kế hệ thống viễn thông', text: 'Thiết kế hệ thống viễn thông' },
  { id: 'Tiếp thị số', text: 'Tiếp thị số' },
  { id: 'Trang điểm', text: 'Trang điểm' },
  { id: 'Truyền thông', text: 'Truyền thông' },
  { id: 'Tư duy linh hoạt', text: 'Tư duy linh hoạt' },
  { id: 'Tư duy logic', text: 'Tư duy logic' },
  { id: 'Tư duy phản biện', text: 'Tư duy phản biện' },
  { id: 'Tư duy sáng tạo', text: 'Tư duy sáng tạo' },
  { id: 'Tư vấn tài chính', text: 'Tư vấn tài chính' },
  { id: 'Tối ưu hóa hệ thống', text: 'Tối ưu hóa hệ thống' },
  { id: 'Viết lách', text: 'Viết lách' },
  { id: 'Xây dựng', text: 'Xây dựng' },
  { id: 'Xero', text: 'Xero' },
  { id: 'XML', text: 'XML' },
  { id: 'Điều khiển robot', text: 'Điều khiển robot' },
  { id: 'Xử lý ảnh và video', text: 'Xử lý ảnh và video' },
  { id: 'Zendesk', text: 'Zendesk' }
];
