export default [
  { id: '3D Modeling', text: '3D Modeling' },
  { id: 'Adobe Illustrator', text: 'Adobe Illustrator' },
  { id: 'Adobe InDesign', text: 'Adobe InDesign' },
  { id: 'Adobe Photoshop', text: 'Adobe Photoshop' },
  { id: 'Agile Methodologies', text: 'Agile Methodologies' },
  { id: 'Alibaba Cloud', text: 'Alibaba Cloud' },
  { id: 'Animation', text: 'Animation' },
  { id: 'ASP.NET', text: 'ASP.NET' },
  { id: 'Auth0', text: 'Auth0' },
  { id: 'Autodesk AutoCAD', text: 'Autodesk AutoCAD' },
  { id: 'Blockchain', text: 'Blockchain' },
  { id: 'Bokeh', text: 'Bokeh' },
  { id: 'CAD/CAM Design', text: 'CAD/CAM Design' },
  { id: 'Cardano', text: 'Cardano' },
  { id: 'CI/CD', text: 'CI/CD' },
  { id: 'Community Governance', text: 'Community Governance' },
  { id: 'Cloud Computing', text: 'Cloud Computing' },
  { id: 'Computer Vision', text: 'Computer Vision' },
  { id: 'Confluence', text: 'Confluence' },
  { id: 'Containerization', text: 'Containerization' },
  { id: 'CSS', text: 'CSS' },
  { id: 'Cybersecurity', text: 'Cybersecurity' },
  { id: 'D3.js', text: 'D3.js' },
  { id: 'Deep Learning', text: 'Deep Learning' },
  { id: 'DevOps', text: 'DevOps' },
  { id: 'Django', text: 'Django' },
  { id: 'Docker', text: 'Docker' },
  { id: 'DigitalOcean', text: 'DigitalOcean' },
  { id: 'Encryption', text: 'Encryption' },
  { id: 'ERP Systems', text: 'ERP Systems' },
  { id: 'Ethereum', text: 'Ethereum' },
  { id: 'Express.js', text: 'Express.js' },
  { id: 'Firebase', text: 'Firebase' },
  { id: 'Flask', text: 'Flask' },
  { id: 'Flutter', text: 'Flutter' },
  { id: 'Git', text: 'Git' },
  { id: 'GitHub', text: 'GitHub' },
  { id: 'GitLab', text: 'GitLab' },
  { id: 'Go', text: 'Go' },
  { id: 'Google Workspace', text: 'Google Workspace' },
  { id: 'GraphQL', text: 'GraphQL' },
  { id: 'Heroku', text: 'Heroku' },
  { id: 'HTML', text: 'HTML' },
  { id: 'IBM Cloud', text: 'IBM Cloud' },
  { id: 'Incident Response', text: 'Incident Response' },
  { id: 'IPFS', text: 'IPFS' },
  { id: 'Ionic', text: 'Ionic' },
  { id: 'Jenkins', text: 'Jenkins' },
  { id: 'JIRA', text: 'JIRA' },
  { id: 'JWT', text: 'JWT' },
  { id: 'Kanban', text: 'Kanban' },
  { id: 'Keras', text: 'Keras' },
  { id: 'Laravel', text: 'Laravel' },
  { id: 'Lean', text: 'Lean' },
  { id: 'Litecoin', text: 'Litecoin' },
  { id: 'Matplotlib', text: 'Matplotlib' },
  { id: 'Microsoft Teams', text: 'Microsoft Teams' },
  { id: 'Microservices', text: 'Microservices' },
  { id: 'MongoDB', text: 'MongoDB' },
  { id: 'Motion Graphics', text: 'Motion Graphics' },
  { id: 'Netlify', text: 'Netlify' },
  { id: 'NoSQL', text: 'NoSQL' },
  { id: 'Node.js', text: 'Node.js' },
  { id: 'NumPy', text: 'NumPy' },
  { id: 'NFTs', text: 'NFTs' },
  { id: 'OAuth', text: 'OAuth' },
  { id: 'Objective-C', text: 'Objective-C' },
  { id: 'OpenID Connect', text: 'OpenID Connect' },
  { id: 'Oracle Cloud', text: 'Oracle Cloud' },
  { id: 'Pandas', text: 'Pandas' },
  { id: 'Penetration Testing', text: 'Penetration Testing' },
  { id: 'Perl', text: 'Perl' },
  { id: 'Plotly', text: 'Plotly' },
  { id: 'PyTorch', text: 'PyTorch' },
  { id: 'R', text: 'R' },
  { id: 'React Native', text: 'React Native' },
  { id: 'ReactJS', text: 'ReactJS' },
  { id: 'RESTful API', text: 'RESTful API' },
  { id: 'Ruby', text: 'Ruby' },
  { id: 'Ruby on Rails', text: 'Ruby on Rails' },
  { id: 'SAML', text: 'SAML' },
  { id: 'Scikit-learn', text: 'Scikit-learn' },
  { id: 'Scrum', text: 'Scrum' },
  { id: 'Seaborn', text: 'Seaborn' },
  { id: 'Serverless', text: 'Serverless' },
  { id: 'Shell Scripting', text: 'Shell Scripting' },
  { id: 'Smart Contracts', text: 'Smart Contracts' },
  { id: 'Solidity', text: 'Solidity' },
  { id: 'Spring Framework', text: 'Spring Framework' },
  { id: 'SQL', text: 'SQL' },
  { id: 'Swift', text: 'Swift' },
  { id: 'TensorFlow', text: 'TensorFlow' },
  { id: 'Trello', text: 'Trello' },
  { id: 'TypeScript', text: 'TypeScript' },
  { id: 'User Experience Design', text: 'User Experience Design' },
  { id: 'User Interface Design', text: 'User Interface Design' },
  { id: 'Vercel', text: 'Vercel' },
  { id: 'Video Editing', text: 'Video Editing' },
  { id: 'Vue.js', text: 'Vue.js' },
  { id: 'Web3.js', text: 'Web3.js' },
  { id: 'Xamarin', text: 'Xamarin' },
  { id: 'XML', text: 'XML' },
  { id: 'Zoom', text: 'Zoom' },
  { id: 'Agile Methodology', text: 'Agile Methodology' },
  { id: 'AWS', text: 'AWS' },
  { id: 'Bán hàng', text: 'Bán hàng' },
  { id: 'Bảo hiểm', text: 'Bảo hiểm' },
  { id: 'Bảo mật mạng', text: 'Bảo mật mạng' },
  { id: 'Biên tập', text: 'Biên tập' },
  { id: 'Big Data', text: 'Big Data' },
  { id: 'Dịch thuật', text: 'Dịch thuật' },
  { id: 'Giao tiếp', text: 'Giao tiếp' },
  { id: 'Giải quyết xung đột', text: 'Giải quyết xung đột' },
  { id: 'Google Cloud Platform', text: 'Google Cloud Platform' },
  { id: 'HubSpot', text: 'HubSpot' },
  { id: 'Kế toán', text: 'Kế toán' },
  { id: 'Kế toán quản trị', text: 'Kế toán quản trị' },
  { id: 'Kỹ năng SEO', text: 'Kỹ năng SEO' },
  { id: 'Kỹ năng marketing số', text: 'Kỹ năng marketing số' },
  { id: 'Làm tóc', text: 'Làm tóc' },
  { id: 'Làm việc độc lập', text: 'Làm việc độc lập' },
  { id: 'Làm việc nhóm', text: 'Làm việc nhóm' },
  { id: 'Lập trình ASIC', text: 'Lập trình ASIC' },
  { id: 'Lập trình Android', text: 'Lập trình Android' },
  { id: 'Lập trình C#', text: 'Lập trình C#' },
  { id: 'Lập trình C++', text: 'Lập trình C++' },
  { id: 'Lập trình FPGA', text: 'Lập trình FPGA' },
  { id: 'Lập trình iOS', text: 'Lập trình iOS' },
  { id: 'Lập trình Java', text: 'Lập trình Java' },
  { id: 'Lập trình JavaScript', text: 'Lập trình JavaScript' },
  { id: 'Lập trình Kotlin', text: 'Lập trình Kotlin' },
  { id: 'Lập trình PHP', text: 'Lập trình PHP' },
  { id: 'Lập trình PLC', text: 'Lập trình PLC' },
  { id: 'Lập trình Python', text: 'Lập trình Python' },
  { id: 'Lập trình Swift', text: 'Lập trình Swift' },
  { id: 'Lập trình TypeScript', text: 'Lập trình TypeScript' },
  { id: 'Lập trình game', text: 'Lập trình game' },
  { id: 'Lập trình máy tính', text: 'Lập trình máy tính' },
  { id: 'Lập trình nhúng', text: 'Lập trình nhúng' },
  { id: 'Lập trình vi xử lý', text: 'Lập trình vi xử lý' },
  { id: 'Lập trình web', text: 'Lập trình web' },
  { id: 'Lập trình ứng dụng di động', text: 'Lập trình ứng dụng di động' },
  { id: 'Lean Methodology', text: 'Lean Methodology' },
  { id: 'Machine Learning', text: 'Machine Learning' },
  { id: 'Marketing', text: 'Marketing' },
  { id: 'May vá', text: 'May vá' },
  { id: 'Microsoft Azure', text: 'Microsoft Azure' },
  { id: 'Microsoft Dynamics', text: 'Microsoft Dynamics' },
  { id: 'Nấu ăn', text: 'Nấu ăn' },
  { id: 'Natural Language Processing', text: 'Natural Language Processing' },
  { id: 'NetSuite', text: 'NetSuite' },
  { id: 'Ngân hàng', text: 'Ngân hàng' },
  { id: 'Ngoại ngữ', text: 'Ngoại ngữ' },
  { id: 'Pha chế', text: 'Pha chế' },
  { id: 'Phân tích an ninh mạng', text: 'Phân tích an ninh mạng' },
  { id: 'Phân tích tài chính', text: 'Phân tích tài chính' },
  { id: 'Phát triển phần mềm', text: 'Phát triển phần mềm' },
  { id: 'Phát triển web', text: 'Phát triển web' },
  { id: 'Phát triển ứng dụng di động', text: 'Phát triển ứng dụng di động' },
  { id: 'Quản lý chuỗi cung ứng', text: 'Quản lý chuỗi cung ứng' },
  { id: 'Quản lý dự án', text: 'Quản lý dự án' },
  { id: 'Quản lý dự án phần mềm', text: 'Quản lý dự án phần mềm' },
  { id: 'Quản lý nhà hàng', text: 'Quản lý nhà hàng' },
  { id: 'Quản lý nhân sự', text: 'Quản lý nhân sự' },
  { id: 'Quản lý khách sạn', text: 'Quản lý khách sạn' },
  { id: 'Quản lý sản xuất', text: 'Quản lý sản xuất' },
  { id: 'Quản lý thời gian', text: 'Quản lý thời gian' },
  { id: 'Quản lý vận hành', text: 'Quản lý vận hành' },
  { id: 'Quản trị cơ sở dữ liệu', text: 'Quản trị cơ sở dữ liệu' },
  { id: 'Quản trị hệ thống', text: 'Quản trị hệ thống' },
  { id: 'Quản trị mạng', text: 'Quản trị mạng' },
  { id: 'Quản trị tài nguyên', text: 'Quản trị tài nguyên' },
  { id: 'Quan hệ công chúng', text: 'Quan hệ công chúng' },
  { id: 'Quảng cáo', text: 'Quảng cáo' },
  { id: 'QuickBooks', text: 'QuickBooks' },
  { id: 'Salesforce', text: 'Salesforce' },
  { id: 'Six Sigma', text: 'Six Sigma' },
  { id: 'Soạn thảo', text: 'Soạn thảo' },
  { id: 'Sửa chữa ô tô', text: 'Sửa chữa ô tô' },
  { id: 'Sửa chữa điện lạnh', text: 'Sửa chữa điện lạnh' },
  { id: 'Sửa chữa điện tử', text: 'Sửa chữa điện tử' },
  { id: 'Sửa chữa máy tính', text: 'Sửa chữa máy tính' },
  { id: 'Tạo nội dung', text: 'Tạo nội dung' },
  { id: 'Thiết kế UX/UI', text: 'Thiết kế UX/UI' },
  { id: 'Thiết kế cơ sở dữ liệu', text: 'Thiết kế cơ sở dữ liệu' },
  { id: 'Thiết kế mạch điện', text: 'Thiết kế mạch điện' },
  { id: 'Thiết kế mạng máy tính', text: 'Thiết kế mạng máy tính' },
  { id: 'Thiết kế nội thất', text: 'Thiết kế nội thất' },
  { id: 'Thiết kế PCB', text: 'Thiết kế PCB' },
  { id: 'Thiết kế thời trang', text: 'Thiết kế thời trang' },
  { id: 'Thiết kế vi mạch', text: 'Thiết kế vi mạch' },
  { id: 'Thiết kế web', text: 'Thiết kế web' },
  { id: 'Thiết kế đồ họa', text: 'Thiết kế đồ họa' },
  { id: 'Thị trường tài chính', text: 'Thị trường tài chính' },
  { id: 'Thiết kế hệ thống viễn thông', text: 'Thiết kế hệ thống viễn thông' },
  { id: 'Tiếp thị số', text: 'Tiếp thị số' },
  { id: 'Trang điểm', text: 'Trang điểm' },
  { id: 'Truyền thông', text: 'Truyền thông' },
  { id: 'Tư duy linh hoạt', text: 'Tư duy linh hoạt' },
  { id: 'Tư duy logic', text: 'Tư duy logic' },
  { id: 'Tư duy phản biện', text: 'Tư duy phản biện' },
  { id: 'Tư duy sáng tạo', text: 'Tư duy sáng tạo' },
  { id: 'Tư vấn tài chính', text: 'Tư vấn tài chính' },
  { id: 'Tối ưu hóa hệ thống', text: 'Tối ưu hóa hệ thống' },
  { id: 'Viết lách', text: 'Viết lách' },
  { id: 'Xero', text: 'Xero' },
  { id: 'Điều khiển robot', text: 'Điều khiển robot' },
  { id: 'Xử lý ảnh và video', text: 'Xử lý ảnh và video' },
  { id: 'Zendesk', text: 'Zendesk' },
  // Administrative Resume Keywords
  { id: 'Quản lý văn phòng', text: 'Quản lý văn phòng' },
  { id: 'Lễ tân', text: 'Lễ tân' },
  { id: 'Trả lời điện thoại', text: 'Trả lời điện thoại' },
  { id: 'Đánh máy các ghi chú', text: 'Đánh máy các ghi chú' },
  { id: 'Trợ lý cá nhân', text: 'Trợ lý cá nhân' },
  { id: 'Lập lịch họp', text: 'Lập lịch họp' },
  { id: 'Đặt hàng văn phòng phẩm', text: 'Đặt hàng văn phòng phẩm' },
  { id: 'Kiểm kê', text: 'Kiểm kê' },
  { id: 'Trợ lý điều hành', text: 'Trợ lý điều hành' },
  { id: 'Lịch trình du lịch', text: 'Lịch trình du lịch' },
  { id: 'Đặt món ăn', text: 'Đặt món ăn' },
  { id: 'Sắp xếp tài liệu', text: 'Sắp xếp tài liệu' },
  { id: 'Giao tiếp với khách hàng', text: 'Giao tiếp với khách hàng' },
  { id: 'Microsoft Word', text: 'Microsoft Word' },
  { id: 'Microsoft Excel', text: 'Microsoft Excel' },
  { id: 'Microsoft Outlook', text: 'Microsoft Outlook' },
  { id: 'Microsoft PowerPoint', text: 'Microsoft PowerPoint' },
  { id: 'Google Docs', text: 'Google Docs' },
  { id: 'Kiểm tra lỗi', text: 'Kiểm tra lỗi' },
  { id: 'Bảo mật thông tin', text: 'Bảo mật thông tin' },
  { id: 'Tổ chức', text: 'Tổ chức' },
  { id: 'Thích nghi', text: 'Thích nghi' },
  { id: 'Trao đổi thư từ', text: 'Trao đổi thư từ' },
  { id: 'Kiểm tra khách đến', text: 'Kiểm tra khách đến' },
  { id: 'Giao tiếp bằng lời nói', text: 'Giao tiếp bằng lời nói' },
  { id: 'Xử lý văn bản', text: 'Xử lý văn bản' },
  // Computer Programming/IT
  { id: 'Phần cứng', text: 'Phần cứng' },
  { id: 'Linux', text: 'Linux' },
  { id: 'Unix', text: 'Unix' },
  { id: 'Windows', text: 'Windows' },
  { id: 'macOS', text: 'macOS' },
  { id: 'Vé hỗ trợ IT', text: 'Vé hỗ trợ IT' },
  { id: 'Thiết kế chương trình', text: 'Thiết kế chương trình' },
  { id: 'Ứng dụng di động', text: 'Ứng dụng di động' },
  { id: 'Phát triển ứng dụng', text: 'Phát triển ứng dụng' },
  { id: 'Dòng lệnh', text: 'Dòng lệnh' },
  { id: 'Lập trình viên Front-end', text: 'Lập trình viên Front-end' },
  { id: 'Lập trình viên Back-end', text: 'Lập trình viên Back-end' },
  { id: 'Lập trình viên Full-stack', text: 'Lập trình viên Full-stack' },
  { id: 'Học máy', text: 'Học máy' },
  { id: 'Trí tuệ nhân tạo', text: 'Trí tuệ nhân tạo' },
  { id: 'Thực tế ảo', text: 'Thực tế ảo' },
  { id: 'Mạng không dây', text: 'Mạng không dây' },
  { id: 'Khoa học dữ liệu', text: 'Khoa học dữ liệu' },
  { id: 'Cơ sở dữ liệu', text: 'Cơ sở dữ liệu' },
  { id: 'Giao diện đồ họa người dùng', text: 'Giao diện đồ họa người dùng' },
  { id: 'Giao diện lập trình ứng dụng', text: 'Giao diện lập trình ứng dụng' },
  { id: 'Cấu hình', text: 'Cấu hình' },
  { id: 'Hệ điều hành', text: 'Hệ điều hành' },
  { id: 'Bash', text: 'Bash' },
  { id: 'Shell', text: 'Shell' },
  // Engineering
  { id: 'Phân tích', text: 'Phân tích' },
  { id: 'CAD', text: 'CAD' },
  { id: 'FEA', text: 'FEA' },
  { id: 'CFD', text: 'CFD' },
  { id: 'Phân tích cấu trúc', text: 'Phân tích cấu trúc' },
  { id: 'Kiểm tra', text: 'Kiểm tra' },
  { id: 'Kỹ sư BS', text: 'Kỹ sư BS' },
  { id: 'Hàng không vũ trụ', text: 'Hàng không vũ trụ' },
  { id: 'Ô tô', text: 'Ô tô' },
  { id: 'Phân tích căng', text: 'Phân tích căng' },
  { id: 'Thiết kế', text: 'Thiết kế' },
  { id: 'Đóng gói', text: 'Đóng gói' },
  { id: 'Quy trình kiểm tra', text: 'Quy trình kiểm tra' },
  { id: 'Kỹ sư dân dụ', text: 'Kỹ sư dân dụ' },
  { id: 'Kỹ sư cơ khí', text: 'Kỹ sư cơ khí' },
  { id: 'Kỹ sư hóa học', text: 'Kỹ sư hóa học' },
  { id: 'Kiểm tra phòng thí nghiệm', text: 'Kiểm tra phòng thí nghiệm' },
  { id: 'Máy móc', text: 'Máy móc' },
  { id: 'Kỹ sư công nghiệp', text: 'Kỹ sư công nghiệp' },
  { id: 'Kỹ sư điện', text: 'Kỹ sư điện' },
  { id: 'Kỹ sư máy tính', text: 'Kỹ sư máy tính' },
  { id: 'Lập trình', text: 'Lập trình' },
  { id: 'Robot', text: 'Robot' },
  { id: 'Kỹ sư chuyên nghiệp', text: 'Kỹ sư chuyên nghiệp' },
  { id: 'Tối ưu hóa', text: 'Tối ưu hóa' },
  { id: 'Xác thực', text: 'Xác thực' },
  { id: 'Xây dựng', text: 'Xây dựng' },
  { id: 'Hạ tầng', text: 'Hạ tầng' },
  { id: 'Điện tử', text: 'Điện tử' },
  { id: 'Tích hợp', text: 'Tích hợp' },
  { id: 'Công nghệ', text: 'Công nghệ' },
  { id: 'Phần mềm', text: 'Phần mềm' },
  { id: 'Khai thác', text: 'Khai thác' },
  { id: 'Kỹ sư địa chất', text: 'Kỹ sư địa chất' },
  { id: 'Kỹ sư môi trường', text: 'Kỹ sư môi trường' },
  { id: 'Cơ điện tử', text: 'Cơ điện tử' },
  // Finance
  { id: 'Bảng tính', text: 'Bảng tính' },
  { id: 'Đối soát ngân hàng', text: 'Đối soát ngân hàng' },
  { id: 'Kế toán viên', text: 'Kế toán viên' },
  { id: 'CPA', text: 'CPA' },
  { id: 'Kế toán viên chứng chỉ', text: 'Kế toán viên chứng chỉ' },
  { id: 'Dòng tiền', text: 'Dòng tiền' },
  { id: 'Phân tích dữ liệu', text: 'Phân tích dữ liệu' },
  { id: 'Quản lý Lợi nhuận & Lỗ', text: 'Quản lý Lợi nhuận & Lỗ' },
  { id: 'Lập kế hoạch', text: 'Lập kế hoạch' },
  { id: 'Tuân thủ', text: 'Tuân thủ' },
  { id: 'Định giá', text: 'Định giá' },
  { id: 'Lập kế hoạch kinh doanh', text: 'Lập kế hoạch kinh doanh' },
  { id: 'Tài chính doanh nghiệp', text: 'Tài chính doanh nghiệp' },
  { id: 'Sáp nhập và mua lại', text: 'Sáp nhập và mua lại' },
  { id: 'Dự báo', text: 'Dự báo' },
  { id: 'Mô hình tài chính', text: 'Mô hình tài chính' },
  { id: 'Kinh tế học', text: 'Kinh tế học' },
  { id: 'SAP', text: 'SAP' },
  { id: 'Lập hóa đơn', text: 'Lập hóa đơn' },
  // Healthcare
  { id: 'Hộ sinh', text: 'Hộ sinh' },
  { id: 'Bác sĩ y khoa', text: 'Bác sĩ y khoa' },
  { id: 'Chuyên gia', text: 'Chuyên gia' },
  { id: 'Người lấy mẫu máu', text: 'Người lấy mẫu máu' },
  {
    id: 'Nhân viên chăm sóc sức khỏe cá nhân',
    text: 'Nhân viên chăm sóc sức khỏe cá nhân'
  },
  { id: 'Chăm sóc bệnh nhân', text: 'Chăm sóc bệnh nhân' },
  { id: 'Đội ngũ y tế', text: 'Đội ngũ y tế' },
  {
    id: 'Đấu tranh cho quyền lợi của bệnh nhân',
    text: 'Đấu tranh cho quyền lợi của bệnh nhân'
  },
  { id: 'Tồn kho bệnh viện', text: 'Tồn kho bệnh viện' },
  { id: 'Phân tích sức khỏe', text: 'Phân tích sức khỏe' },
  { id: 'Hoạt động chăm sóc sức khỏe', text: 'Hoạt động chăm sóc sức khỏe' },
  { id: 'Bác sĩ', text: 'Bác sĩ' },
  { id: 'Nha sĩ vệ sinh răng miệng', text: 'Nha sĩ vệ sinh răng miệng' },
  { id: 'Nha sĩ', text: 'Nha sĩ' },
  { id: 'Hồ sơ y tế', text: 'Hồ sơ y tế' },
  { id: 'Hợp tác của đội ngũ y tế', text: 'Hợp tác của đội ngũ y tế' },
  { id: 'Cảm thông', text: 'Cảm thông' },
  { id: 'Phẫu thuật', text: 'Phẫu thuật' },
  { id: 'Phòng mổ', text: 'Phòng mổ' },
  { id: 'Dược sĩ', text: 'Dược sĩ' },
  { id: 'Bác sĩ thực tập', text: 'Bác sĩ thực tập' },
  { id: 'Chủ nhiệm nghiên cứu', text: 'Chủ nhiệm nghiên cứu' },
  { id: 'Lắng nghe', text: 'Lắng nghe' },
  { id: 'Chú ý đến chi tiết', text: 'Chú ý đến chi tiết' },
  { id: 'Quản lý đơn thuốc', text: 'Quản lý đơn thuốc' },
  // Human Resources
  { id: 'Chuyên viên nhân sự', text: 'Chuyên viên nhân sự' },
  { id: 'Giữ chân nhân viên', text: 'Giữ chân nhân viên' },
  { id: 'Quy trình tuyển dụng', text: 'Quy trình tuyển dụng' },
  { id: 'Thay đổi tổ chức', text: 'Thay đổi tổ chức' },
  { id: 'Quản lý thay đổi', text: 'Quản lý thay đổi' },
  { id: 'Đàm phán hợp đồng', text: 'Đàm phán hợp đồng' },
  { id: 'Phát triển cấp cao', text: 'Phát triển cấp cao' },
  { id: 'Tương tác nhân viên', text: 'Tương tác nhân viên' },
  { id: 'Phỏng vấn ra đi', text: 'Phỏng vấn ra đi' },
  { id: 'Chuyên viên nhân sự tổng hợp', text: 'Chuyên viên nhân sự tổng hợp' },
  { id: 'Phỏng vấn', text: 'Phỏng vấn' },
  { id: 'Mô tả công việc', text: 'Mô tả công việc' },
  // Legal
  { id: 'Trợ lý luật sư', text: 'Trợ lý luật sư' },
  { id: 'Luật pháp thử', text: 'Luật pháp thử' },
  { id: 'Luật gia đình', text: 'Luật gia đình' },
  { id: 'Luật tổn thương', text: 'Luật tổn thương' },
  { id: 'Kiện tụng', text: 'Kiện tụng' },
  { id: 'Viết văn bản pháp lý', text: 'Viết văn bản pháp lý' },
  { id: 'Luật lao động', text: 'Luật lao động' },
  { id: 'Sở hữu trí tuệ', text: 'Sở hữu trí tuệ' },
  { id: 'Đánh giá pháp lý', text: 'Đánh giá pháp lý' },
  { id: 'Pháp luật', text: 'Pháp luật' },
  { id: 'Chiến lược vụ án', text: 'Chiến lược vụ án' },
  { id: 'Nghiên cứu pháp lý', text: 'Nghiên cứu pháp lý' },
  { id: 'Đệ trình yêu cầu', text: 'Đệ trình yêu cầu' },
  { id: 'Thư ký pháp lý', text: 'Thư ký pháp lý' },
  { id: 'Đệ trình điện tử', text: 'Đệ trình điện tử' },
  { id: 'Cấp phép', text: 'Cấp phép' },
  { id: 'Luật bản quyền', text: 'Luật bản quyền' },
  { id: 'Giải quyết hòa giải', text: 'Giải quyết hòa giải' },
  { id: 'Tuyên thệ', text: 'Tuyên thệ' },
  { id: 'Đàm phán', text: 'Đàm phán' },
  { id: 'Luật hợp đồng', text: 'Luật hợp đồng' },
  { id: 'Công tố viên', text: 'Công tố viên' },
  { id: 'Thẩm phán', text: 'Thẩm phán' },
  { id: 'Nói công khai', text: 'Nói công khai' },
  { id: 'Luật hình sự', text: 'Luật hình sự' },
  // Management
  { id: 'Lãnh đạo', text: 'Lãnh đạo' },
  { id: 'Quản lý', text: 'Quản lý' },
  { id: 'Truyền cảm hứng', text: 'Truyền cảm hứng' },
  { id: 'Xây dựng đội ngũ', text: 'Xây dựng đội ngũ' },
  { id: 'Văn hóa công ty', text: 'Văn hóa công ty' },
  { id: 'Ban điều hành', text: 'Ban điều hành' },
  { id: 'Khởi nghiệp', text: 'Khởi nghiệp' },
  { id: 'Quản lý ngân sách', text: 'Quản lý ngân sách' },
  { id: 'Hướng kinh doanh', text: 'Hướng kinh doanh' },
  { id: 'Quản lý hoạt động', text: 'Quản lý hoạt động' },
  { id: 'Phát triển chính sách', text: 'Phát triển chính sách' },
  { id: 'Quản lý tài sản', text: 'Quản lý tài sản' },
  { id: 'Đề xuất', text: 'Đề xuất' },
  { id: 'Vận hành logistics', text: 'Vận hành logistics' },
  { id: 'Tuyên bố sứ mệnh công ty', text: 'Tuyên bố sứ mệnh công ty' },
  { id: 'Phân tích kinh doanh', text: 'Phân tích kinh doanh' },
  { id: 'Quản lý quy trình làm việc', text: 'Quản lý quy trình làm việc' },
  { id: 'Đánh giá hiệu suất', text: 'Đánh giá hiệu suất' },
  { id: 'Đối tác', text: 'Đối tác' },
  { id: 'Quản lý tài khoản', text: 'Quản lý tài khoản' },
  { id: 'Cơ quan quản lý cổ đông', text: 'Cơ quan quản lý cổ đông' },
  { id: 'Mối quan hệ với nhà cung cấp', text: 'Mối quan hệ với nhà cung cấp' },
  { id: 'Kiểm toán', text: 'Kiểm toán' },
  { id: 'Quản lý rủi ro', text: 'Quản lý rủi ro' },
  { id: 'Chỉ đạo', text: 'Chỉ đạo' },
  { id: 'Giám sát', text: 'Giám sát' },
  // Manufacturing, Industrial, and Technical
  { id: 'Hàn', text: 'Hàn' },
  { id: 'Bảo trì', text: 'Bảo trì' },
  { id: 'Dịch vụ', text: 'Dịch vụ' },
  { id: 'Thợ điện', text: 'Thợ điện' },
  { id: 'Thang máy', text: 'Thang máy' },
  { id: 'Hệ thống HVAC', text: 'Hệ thống HVAC' },
  { id: 'Bảo trì tòa nhà', text: 'Bảo trì tòa nhà' },
  { id: 'Thợ điện tử', text: 'Thợ điện tử' },
  { id: 'Xử lý sự cố', text: 'Xử lý sự cố' },
  { id: 'Giải quyết vấn đề', text: 'Giải quyết vấn đề' },
  { id: 'Sản xuất gọn nhẹ', text: 'Sản xuất gọn nhẹ' },
  { id: 'Giao nhận hàng', text: 'Giao nhận hàng' },
  { id: 'Kiểm soát chất lượng', text: 'Kiểm soát chất lượng' },
  { id: 'Kiểm định chất lượng', text: 'Kiểm định chất lượng' },
  { id: 'Kho', text: 'Kho' },
  { id: 'Thợ mộc', text: 'Thợ mộc' },
  { id: 'Thợ sửa ống nước', text: 'Thợ sửa ống nước' },
  { id: 'Dụng cụ', text: 'Dụng cụ' },
  { id: 'Vận chuyển hàng hóa', text: 'Vận chuyển hàng hóa' },
  { id: 'Quản lý an toàn', text: 'Quản lý an toàn' },
  // Sales and Marketing
  { id: 'Marketing số', text: 'Marketing số' },
  { id: 'SEM', text: 'SEM' },
  { id: 'Marketing nội dung', text: 'Marketing nội dung' },
  { id: 'Mối quan hệ khách hàng', text: 'Mối quan hệ khách hàng' },
  { id: 'CRM', text: 'CRM' },
  { id: 'Lịch biên tập', text: 'Lịch biên tập' },
  { id: 'Blog', text: 'Blog' },
  { id: 'Hài lòng khách hàng', text: 'Hài lòng khách hàng' },
  { id: 'Phát triển kinh doanh', text: 'Phát triển kinh doanh' },
  { id: 'Cuộc gọi bán hàng', text: 'Cuộc gọi bán hàng' },
  { id: 'B2B', text: 'B2B' },
  { id: 'B2C', text: 'B2C' },
  { id: 'Ra mắt sản phẩm', text: 'Ra mắt sản phẩm' },
  { id: 'Email marketing', text: 'Email marketing' },

  //others
  { id: 'OOP', text: 'OOP' },
  { id: 'MySQL', text: 'MySQL' },
  { id: 'Oracle Database', text: 'Oracle Database' },
  { id: 'MongoDB', text: 'MongoDB' },
  { id: 'PostgreSQL', text: 'PostgreSQL' },
  { id: 'Microsoft SQL Server', text: 'Microsoft SQL Server' },
  { id: 'SQLite', text: 'SQLite' },
  { id: 'Unit Test', text: 'Unit Test' },
  { id: 'Project Manager', text: 'Project Manager' },
  { id: 'Product Owner', text: 'Product Owner' },
  { id: 'IT Business Analyst', text: 'IT Business Analyst' },
  { id: 'Tin học văn phòng', text: 'Tin học văn phòng' },
  { id: 'Giao tiếp tốt', text: 'Giao tiếp tốt' },
  { id: 'Chăm sóc khách hàng', text: 'Chăm sóc khách hàng' },
  { id: 'Telesale', text: 'Telesale' },
  { id: 'Trade Marketing', text: 'Trade Marketing' },
  { id: 'Sáng tạo', text: 'Sáng tạo' },
  { id: 'Năng động', text: 'Năng động' },
  { id: 'Tiếng Anh', text: 'Tiếng Anh' },
  { id: 'Tiếng Nhật', text: 'Tiếng Nhật' },
  { id: 'Tiếng Hàn', text: 'Tiếng Hàn' },
  { id: 'Tiếng Trung', text: 'Tiếng Trung' },
  { id: 'Tiếng Pháp', text: 'Tiếng Pháp' },
  { id: 'Tiếng Tây Ban Nha', text: 'Tiếng Tây Ban Nha' },
  { id: 'Kỷ năng lãnh đạo', text: 'Kỷ năng lãnh đạo' },
  { id: 'WordPress', text: 'WordPress' },
  { id: 'Chịu áp lực', text: 'Chịu áp lực' },
  { id: 'Ham học hỏi', text: 'Ham học hỏi' },
  { id: 'Hòa nhã', text: 'Hòa nhã' },
  { id: 'Trung thực', text: 'Trung thực' },
  { id: 'Kỷ luật cao', text: 'Kỷ luật cao' },
  { id: 'Golang', text: 'Golang' },
  { id: 'Unity', text: 'Unity' },
  { id: 'Kafka', text: 'Kafka' },
  { id: 'Apache Spark', text: 'Apache Spark' },
  { id: 'Kubernetes', text: 'Kubernetes' },
  { id: 'Data Mining', text: 'Data Mining' },
  { id: 'NLP', text: 'NLP' },
  { id: 'Kanban', text: 'Kanban' },
  { id: 'Social Media', text: 'Social Media' },
  { id: 'Kiểm thử phần mềm', text: 'Kiểm thử phần mềm' },
  {
    id: 'Nghiên cứu và phát triển (R&D)',
    text: 'Nghiên cứu và phát triển (R&D)'
  }
];
